let shopItemsData = [
    {
      id: "jfhgbvnscs40",
      name: "Guest Car per day",
      price: 10000,
      desc: "",
      img: "te1.jpeg",
    },
    {
      id: "ioytrhndcv41",
      name: "Bus transportation per day",
      price: 15000,
      desc: "A minimum of 5 luxury buses for mass transportation",
      img: "te2.jpeg",
    },
    {
      id: "wuefbncxbsn42",
      name: "single music System car",
      price: 17000,
      desc: "An executive jeep with music system for raries",
      img: "te3.jpeg",
    },
    {
      id: "thyfhcbcv43",
      name: "Road trucks",
      price: 100000,
      desc: "Comes with a full stage and advertisement space",
      img: "te4.jpeg",
    },
    
    {
      id: "thyfhcbcv44",
      name: "Road trucks",
      price: 50000,
      desc: "Comes with a full stage and advertisement space",
      img: "te5.jpeg",
    },
    {
      id: "thyfhcbcv45",
      name: "Road trucks",
      price: 40000,
      desc: "Comes with a full stage and advertisement space",
      img: "te6.jpeg",
    },
    {
        id: "thyfhcbcv46",
        name: "Road trucks",
        price: 55000,
        desc: "Comes with a full stage and advertisement space",
        img: "te7.jpeg",
      },
      {
        id: "thyfhcbcv47",
        name: "Road trucks",
        price: 45000,
        desc: "Comes with a full stage and advertisement space",
        img: "te8.jpeg",
      },
      {
        id: "thyfhcbcv48",
        name: "Road trucks",
        price: 60000,
        desc: "Comes with a full stage and advertisement space",
        img: "te9.jpeg",
      },
      {
        id: "thyfhcbcv49",
        name: "Road trucks",
        price: 70000,
        desc: "Comes with a full stage and advertisement space",
        img: "te10.jpeg",
      },
      {
        id: "thyfhcbcv50",
        name: "Road trucks",
        price: 66000,
        desc: "Comes with a full stage and advertisement space",
        img: "te11.jpeg",
      },
      {
        id: "thyfhcbcv51",
        name: "Road trucks",
        price: 30000,
        desc: "Comes with a full stage and advertisement space",
        img: "te12.jpeg",
      },
      {
        id: "thyfhcbcv52",
        name: "Road trucks",
        price: 75000,
        desc: "Comes with a full stage and advertisement space",
        img: "te13.jpeg",
      },

  ];